version: '3'
services:
  # client:
  #   container_name: gr-frontend
  #   build: './client'
  #   ports:
  #     - 3000:3000
  server:
    image: node
    container_name: goodreactions
    working_dir: /app
    environment:
      - DATABASE_URL=postgres://goodreactions:r34c710n5@db:5432/highscores
      - NODE_ENV=development
    ports:
      - 8080:8080
    depends_on:
      - db
      # - client
    volumes:
      - type: bind
        source: .
        target: /app
    command: bash -c "npm i && npm run dev && npm run db"
    
  db:
    image: postgres:latest
    volumes:
      - "./db/migrations:/docker-entrypoint-initdb.d/:ro"
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=highscores
      - POSTGRES_USER=goodreactions
      - POSTGRES_PASSWORD=r34c710n5
volumes:
  dbdata:
networks:
  default:
    name: goodreactions